[build]
  publish = "frontend/build"
  command = "./build.sh"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  NPM_CONFIG_PRODUCTION = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Explicitly set React project environment
  REACT_APP_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  # Prevent any Angular-related tooling
  SKIP_PREFLIGHT_CHECK = "true"
  DISABLE_ESLINT_PLUGIN = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.processing.optimization]
  bundle = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend && npm start"
  port = 3000
  publish = "frontend/build" 