[build]
  publish = "frontend/build"
  command = "git submodule update --init --recursive && cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  NPM_CONFIG_PRODUCTION = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend && npm start"
  port = 3000
  publish = "frontend/build"

# Build processing configuration
[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Build timeout and optimization
[build.processing.optimization]
  bundle = true

# Build hooks for submodule handling
[build.processing.hooks]
  pre_build = "git submodule update --init --recursive"

# Build timeout configuration
[build.processing.timeout]
  timeout = 600

# Build hooks for submodule handling
[build.processing.hooks]
  post_build = "echo 'Build completed successfully'"

# Build hooks for submodule handling
[build.processing.hooks]
  on_success = "echo 'Deployment successful'" 