[build]
  publish = "frontend/build"
  command = "git submodule update --init --recursive && cd frontend && npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  NPM_CONFIG_PRODUCTION = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend && npm start"
  port = 3000
  publish = "frontend/build"

# Build timeout configuration
[build.processing.html]
  pretty_urls = true

# Build hooks for submodule handling
[build.processing.images]
  compress = true

# Build hooks for submodule handling
[build.processing.skip_processing]
  skip_processing = false 